name: Example using action 'opt-nc/domaine-nc-action' with an issue creation

on:
  workflow_dispatch:
    inputs:        
      domain:
        description: Domain name without extenstion
        required: true
        type: choice
        default: opt
        options:
        - opt
        - domain
        - '1012'
        - ccp
      daysBeforeExpiration:
        description: Days before domain expiration that triggers new issue
        required: true
        default: '5'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call the action
        uses: opt-nc/domaine-nc-action@v1
        id: meta
        with:
          api-key: ${{ secrets.RAPID_API_KEY }}
          name: ${{ github.event.inputs.domain }}

      - name: Create an warning ⚠️ issue if needed
        if: ${{ steps.meta.outputs.expired == 'false' && steps.meta.outputs.daysBeforeExpiration <= github.event.inputs.daysBeforeExpiration }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.repository }}'.split('/')[1],
              title: ':warning: Domain ${{ github.event.inputs.domain }}.nc is about to expire :warning:',
              body: ':point_right: ${{ github.event.inputs.domain }}.nc will expire on ${{ steps.meta.outputs.expirationDate }}',
              labels: ['expired-domain']
            });

      - name: Create an alert 🚨 issue if needed
        if: ${{ steps.meta.outputs.expired == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.repository }}'.split('/')[1],
              title: ':rotating_light: Domain ${{ github.event.inputs.domain }}.nc has expired :rotating_light:',
              body: ':point_right: ${{ github.event.inputs.domain }}.nc has expired on ${{ steps.meta.outputs.expirationDate }}',
              labels: ['expired-domain']
            });

